### ISSUE TITLE
Updates from Google Code

### ISSUE THREAD

**Issue by faceleg** [jackcviers/Rangy#1]
Will you be merging in any updates from the Google Code repository?

**Comment by jackcviers** [comment]
Yes. I will be periodically merging those in. I'm using this for a project at my company so I'd like to stay as up to date as possible. I will start scheduling merges from the google code repository twice a week, starting next week. Sorry if I'm behind a few updates right now.

**Comment by faceleg** [comment]
Sounds great! We use it too, I'd much rather deal with a Git repository than SVN.

**Comment by jackcviers** [comment]
@faceleg For sure!
